#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# Update the package lists for upgrades and new package installations
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Start nginx
sudo service nginx start

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Create a configuration file for the custom 404 page
echo "server {
    listen 80;
    server_name localhost;

    location = /redirect_me {
        return 301 http://www.example.com;
    }

    location / {
        root /var/www/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}" | sudo tee /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

echo "Nginx is now configured to display a custom 404 page with the string 'Ceci n'est pas une page'."
