#!/usr/bin/env bash
# This script pings an IP address.
# Checking if an argument was passed

if [ "$#" -ne 1 ]; then
echo "Usage: 5-is_the_host_on_the_network {41.215.169.138}"
exit 1
fi
# Ping the IP address 5 times
ping -c 5 "$1"
