#!/usr/bin/env bash
# This script displays list of all currently running processes for all users,
# including those which might not have a TTY. The output is displayed in a
# user-oriented format and shows the process hierarchy.

ps -efH
