#!/usr/bin/env bash
# When passing the argument start:
#	1.Starts manage_my_process
#	2.Creates a file containing its PID in /var/run/my_process.pid
#	3.Displays manage_my_process started
# When passing the argument stop:
#	1.Stops manage_my_process
#	2.Deletes the file /var/run/my_process.pid
#	3.Displays manage_my_process stopped
# When passing the argument restart
#	2.Stops manage_my_process
#	2.Deletes the file /var/run/my_process.pid
#	3.Starts manage_my_process
#	4.Creates a file containing its PID in /var/run/my_process.pid
#	5.Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

case "$1" in
    start)
        manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
