#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# with a 2-second pause between each iteration and prints
# "I am invincible!!!" when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done

# This script stops the 7-highlander process.

pkill -f "7-highlander"
