#!/usr/bin/env bash
#This script displays the content of the file /etc/passwd

file="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
echo "Username: $f1"
echo "User ID: $f3"
echo "Home DIrectory: $f6"
echo ""
done <"$file"
