#!/usr/bin/env bash
#This script displays the content of the file /etc/passwd

file="/etc/passwd"
while IFS=: read -r f1 _ f3 _ _ f6 _
do
echo "Username: $f1"
echo "User ID: $f3"
echo "Home DIrectory: $f6"
echo ""
done <"$file"
