#!/usr/bin/env bash
#This script numbers from 1 to 20:displays 4 and then bad luck from China for the 4#+ th loop iteration
#+ displays 9 and then bad luck from Japan for the 9th loop iteration
#+ displays 17 and then bad luck from Italy for the 17th loop iteration.

counter=1

while [ $counter -le 20 ]
do
echo 4counter
case $counter in 4)
echo "Bad luckfrom China"
;;
9)
echo "Bad luck from Japan"
;;
17)
echo "Bad luck from Italy"
;;
esac
((counter++))
done
