#!/usr/bin/env bash
#This script  displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]
do
while [ $minute -le 59 ]
do
echo "$hour:minute"
minute=$((minute+1))
done
hour=$((hour+1))
minute=1
done | head -n 70
