#!/usr/bin/env bash
# This script modifies an Unbutu server

# Backing up the localhost file
cp /etc/hosts /etc/hosts.bak

# Add the new entries to the hosts file
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
