#!/usr/bin/env bash
# Command to generate the RSA key pair

# Name of the private key
KEY_NAME="school"

# Number of bits in the key
KEY_BITS=4096

# Passphrase for the key
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b ${KEY_BITS} -f ${KEY_NAME} -N ${PASSPHRASE}

echo "RSA key pair has been created."
